# Generated by Django 6.0.3 on 2026-03-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='qnswer',
            new_name='answer',
        ),
    ]
